[workspace]
members = ["programs/*"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "thin"
codegen-units = 4

[profile.release.build-override]
opt-level = 2
incremental = false
codegen-units = 4
